### ISSUE TITLE
Could not use PSIGEL

### ISSUE THREAD

**Issue by bjoernwolter** [falkheiland/PSIGEL#21]
Installed PSIGEL with Install-Module. When i try to run e.g Get-UMSThinclient, i enter the credential and the powershell reports me the following:

Es wurden mehrere nicht eindeutige Überladungen gefunden für "Add" und die Argumentanzahl: "1".
In C:\Program Files\WindowsPowerShell\Modules\psigel\1.3.2\Public\New-UMSAPICookie.ps1:78 Zeichen:7
       $WebSession.Cookies.Add($Cookie)
     CategoryInfo          : NotSpecified: (:) [], MethodException
     FullyQualifiedErrorId : MethodCountCouldNotFindBest

Invoke-RestMethod : "System.Object[]" kann nicht in den Typ "Microsoft.PowerShell.Commands.WebRequestSession" konvertiert werden, der für den Parameter "WebSession"
erforderlich ist. Die angegebene Methode wird nicht unterstützt.
In C:\Program Files\WindowsPowerShell\Modules\psigel\1.3.2\Private\Invoke-UMSRestMethodWebSession.ps1:64 Zeichen:25
       Invoke-RestMethod @PSBoundParameters -ErrorAction Stop
     CategoryInfo          : InvalidArgument: (:) [Invoke-RestMethod], ParameterBindingException
     FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by falkheiland** [comment]
Edit: 
The error is generated when there is either the wrong server (parameter computername - which is not mandatory by now - will be changed in next release) is specified, or the API (IMI) is not licensed.
I suppose with one of the next releases of the UMS the API (IMI) is included - until then you have to license this feature.

You can get an community-nfr license from the [IGEL-Community (Slack)](https://join.slack.com/t/igelcommunity/shared_invite/enQtMjg5MzAzMzkwMjU5LTNmMmYxZDgwNmYwMzAyZTE5NmRjN2Y0NjQxNTkyN2E5ZDZkNzk1M2U0NGE0NGMwZGE3MzU4NjNlNWNjZGUwNDI) though.
