### ISSUE TITLE
New-UMSAPICookie - Self-Signed Certificates

### ISSUE THREAD

**Issue by 4oo4** [falkheiland/PSIGEL#25]
We have a UMS server that's using a self-signed certificate, and it appears that `New-UMSAPICookie`, in using `Invoke-RestMethod` will not make the connection unless the certificate is fully trusted. In Powershell Core 6.0, they add a `-SkipCertificateCheck` option that's not available in Powershell 5.1, so I'm unable to add that to the `Invoke-RestMethod` parameters.

When I try again using Powershell Core 6.0, it appears that the type created for `TrustAllCertsPolicy` no longer works because it relies on `ICertificatePolicy`, which is no longer include in the .Net Core API.(https://github.com/PowerShell/PowerShell/issues/7092#issuecomment-398005195)

So, my question is how to make this work for a self-signed certificate? I would imagine that most people would be running a UMS internally and not be using a fully-trusted certificate, so it would make sense to have an option to disable certificate verification. That would mean that it would need to be compatible with Powershell Core 6.0, though that would mean breaking the .Net API that's used by 5.1.

Would it be possible to add both of the .Net APIs for `ICertificatePolicy` and `ServerCertificateValidationCallback`, and then load the right one based on the Powershell version? Also there would have to be a check for the Powershell version for the `Invoke-RestMethod` parameters, since 5.1 doesn't recognize the `-SkipCertificateCheck` option.

```
Add-Type : (3,40): error CS0246: The type or namespace name 'ICertificatePolicy' could not be found (are you missing a using directive or an assembly reference?)
    public class TrustAllCertsPolicy : ICertificatePolicy {
                                       ^
At C:\Program Files\WindowsPowershell\Modules\psigel\0.9.0\Public\New-UMSAPICookie.ps1:31 char:5
+     Add-Type -TypeDefinition @'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: ((3,40): error CS024\u2026ssembly reference?):CSDiagnostic) [Add-Type], Exception+ FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Cannot add type. Compilation errors occurred.
At C:\Program Files\WindowsPowershell\Modules\psigel\0.9.0\Public\New-UMSAPICookie.ps1:31 char:5
+     Add-Type -TypeDefinition @'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
+ FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand

New-Object : Cannot find type [TrustAllCertsPolicy]: verify that the assembly containing this type is loaded.
At C:\Program Files\WindowsPowershell\Modules\psigel\0.9.0\Public\New-UMSAPICookie.ps1:42 char:52
+ ... anager]::CertificatePolicy = New-Object -TypeName TrustAllCertsPolicy
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
+ FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

The SSL connection could not be established, see inner exception.
Multiple ambiguous overloads found for "Add" and the argument count: "1".
At C:\Program Files\WindowsPowershell\Modules\psigel\0.9.0\Public\New-UMSAPICookie.ps1:83 char:7
+       $WebSession.Cookies.Add($Cookie)
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodException
+ FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

**Comment by falkheiland** [comment]
Which version of PS do you use?
Which version of the UMS do you use?
If you use UMS version < 6.x, do you have the IMI licensed?

Saying that, PSIGEL is tested on (and supported really) only for PS5.1 by now. I will have to update the README.MD to reflect this.
So if you are not using that version, could you do so and test again?
The certificate handling in 5.1 is done in the begin-block of the New-UMSAPICookie function. Since I dont know of a way to use a custom certificate for the UMS-IMI(API), the module is tested with a self-signed certificate only.

**Comment by 4oo4** [comment]
PS Version: 5.1
UMS version: 6.01.130

That makes sense, I wasn't finding a way to use a custom cert either. I'll do some more testing and see if there's anything else causing that SSL error, certificate verification jumped out at me after looking at the `Invoke-WebRequest` wrapper. I'll also try just try that on its own and see if I can find anything out that way.

Cheers

**Comment by falkheiland** [comment]
> ```
>  Add-Type : (3,40): error CS0246: The type or namespace name 'ICertificatePolicy' could not be found > 
> ```

seems to be a error message from >= PS 6.x (at least thats what I found in google) - are you sure you used PS5.1 ?

**Comment by 4oo4** [comment]
Sorry, should have prefaced that was an attempt with 6.0, normally I use 5.1, so this is what I was originally trying to troubleshoot:

```
The request was aborted: Could not create SSL/TLS secure channel.
Multiple ambiguous overloads found for "Add" and the argument count: "1".
At C:\Program Files\WindowsPowerShell\Modules\psigel\0.9.0\Public\New-UMSAPICookie.ps1:82 char:7
+       $WebSession.Cookies.Add($Cookie)
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest



Headers               : {}
Cookies               : System.Net.CookieContainer
UseDefaultCredentials : False
Credentials           :
Certificates          :
UserAgent             : Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.17763.503
Proxy                 :
MaximumRedirection    : -1
```

**Comment by falkheiland** [comment]
do you run the UMS tomcat config ootb? If you changed it to use another TLS version but 1.2, then you can try and use the parameter SecurityProtocol :

> -SecurityProtocol
> Set SSL/TLS protocol
> 
> Type: String[]
> Parameter Sets: (All)
> Aliases:
> Accepted values: Tls12, Tls11, Tls, Ssl3
> 
> Required: False
> Position: 4
> Default value: None
> Accept pipeline input: False
> Accept wildcard characters: False

**Comment by 4oo4** [comment]
Yes, we are using TLS 1.2, I had tried explicitly to give it `-SecurityProtocol Tls12` but that didn't help.

The more I dig into this, the more it looks like an issue deeper than this module. Just a plain `Invoke-RestMethod -uri https://igel-server:8443` fails with a TLS error too. (That's with 5.1, but for some reason the `Invoke-RestMethod` works with Powershell Core 6.x?)

I can also see that looking at the certificate verification was unnecessary, since you already had a way to bypass that, just for some reason my computer doesn't want to do an SSL handshake with our UMS server using the Windows `SCHANNEL` stack. I get a TLS error in IE in addition to Powershell.

Thanks again for looking
