### ISSUE TITLE
New-UMSDeviceDirectory fails with german "Umlaute"

### ISSUE THREAD

**Issue by Binomimus** [falkheiland/PSIGEL#36]
When trying to create a directory with special characters like ä,ö,ü creatin fails, because the sent json is not in an expected format (there are those people who will not refrain from using special chars)

Can be reproduced like this:
New-UMSDeviceDirectory -Computername 'IGELRMSERVER' -WebSession $igelSession -Name 'Böser Umlaut"

This can be fixed by setting expected charset to utf-8 when sending the json request:
ContentType      = 'application/json; charset=utf-8'
(instead of only "ContentType      = 'application/json'")

I changed this in my local version of "New-UMSDeviceDirectory.ps1" (line 45) and everything worked as expected.

Can someone confirm and implement this in upcoming releases?

**Comment by Binomimus** [comment]
possible duplicate to #34

**Comment by falkheiland** [comment]
I am not sure if I properly implement this (would have to build up a dev environment again for the current version).
There is a new major UMS version on the horizon, which comes with a complete new API which I will have to redesign this module for entirely, so I am not really keen in investing for "smaller" bugs.
If it is really important to you to have a fixed version via PSGallery, let me know though.

**Comment by falkheiland** [comment]
#38

**Comment by Binomimus** [comment]
thank you very much :-)

**Comment by falkheiland** [comment]
this is atm only done in the main branch, but there is no new release (neither here on Github, nor on the PSGallery) .

since the version change from IGEL is not going to change the API to a meaningful extent, i will restructure the whole project sooner and only after this is done there will be new releases and proper testing.
